import { concat, conditions, defineMatrix, step, workflow } from "@david/gagen";

const header = "# GENERATED by .github/workflows/ci.ts -- do not edit manually";

const checkout = step({ uses: "actions/checkout@v6" });
const setupDeno = step({
  name: "Install deno",
  uses: "denoland/setup-deno@v2",
  with: { "deno-version": "2.x" },
});

const isLinux = conditions.isRunnerOs("Linux");
const isTag = conditions.isTag();

const matrix = defineMatrix({
  os: ["ubuntu-latest", "macOS-latest", "windows-latest"],
});

const getTagVersion = step({
  id: "get_tag_version",
  name: "Get tag version",
  if: isTag,
  run: "echo TAG_VERSION=${GITHUB_REF/refs\\/tags\\//} >> $GITHUB_OUTPUT",
  outputs: ["TAG_VERSION"],
}).dependsOn(checkout);

workflow({
  name: "ci",
  on: {
    push: { branches: ["main"], tags: ["*"] },
    pull_request: {},
  },
  concurrency: {
    group: "${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}",
    cancelInProgress: true,
  },
  jobs: [
    {
      id: "test",
      name: concat("shell-", matrix.os),
      runsOn: matrix.os,
      permissions: { contents: "read" },
      timeoutMinutes: 30,
      strategy: { matrix },
      steps: [
        checkout,
        setupDeno,
        {
          uses: "actions/setup-node@v6",
          with: { "node-version": "24.x" },
        },
        { uses: "dprint/check@v2.3", if: isLinux },
        { name: "lint", if: isLinux, run: "deno lint" },
        { name: "check", if: isLinux, run: "deno check --all" },
        { name: "lint ci", if: isLinux, run: "deno run -A @david/gagen --lint" },
        { name: "deno test", run: "deno test -P" },
        { name: "node test", run: "deno task test:node" },
      ],
    },
    {
      id: "npm",
      runsOn: "ubuntu-latest",
      permissions: { contents: "read", "id-token": "write" },
      timeoutMinutes: 30,
      steps: [
        checkout,
        setupDeno,
        {
          uses: "actions/setup-node@v6",
          with: {
            "node-version": "24.x",
            "registry-url": "https://registry.npmjs.org",
          },
        },
        getTagVersion,
        {
          name: "npm build",
          run: `deno task dnt ${getTagVersion.outputs.TAG_VERSION}`,
        },
        {
          name: "npm publish",
          if: isTag,
          run: "cd npm && npm publish --access public",
        },
      ],
    },
    {
      id: "jsr",
      runsOn: "ubuntu-latest",
      permissions: { contents: "read", "id-token": "write" },
      steps: [
        checkout,
        setupDeno,
        {
          name: "Publish to JSR on tag",
          run: "deno run -A jsr:@david/publish-on-tag@0.2.0",
        },
      ],
    },
  ],
}).writeOrLint({
  filePath: new URL("./ci.generated.yml", import.meta.url),
  header,
});
